FROM python:3.11-slim

WORKDIR /app

COPY server.py .

# Default env vars
ENV OUTPUT_PATH="/app/out"

# Create output dir (expected to be mounted)
RUN mkdir -p /app/out

EXPOSE 5000

CMD ["python3", "server.py"]
